force-app/solution/03_DataModel/objects/Opportunity/fields/AmountAfterDiscount__c.field-meta.xml
<CustomField>
    <fullName>AmountAfterDiscount__c</fullName>
    <label>Amount After Discount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/solution/03_DataModel/objects/Opportunity/fields/DiscountPercent__c.field-meta.xml
<CustomField>
    <fullName>DiscountPercent__c</fullName>
    <label>Discount Percent</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/solution/03_DataModel/objects/Opportunity/fields/VehicleBrand__c.field-meta.xml
<CustomField>
    <fullName>VehicleBrand__c</fullName>
    <label>Vehicle Brand</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/solution/03_DataModel/objects/Opportunity/fields/VehicleType__c.field-meta.xml
<CustomField>
    <fullName>VehicleType__c</fullName>
    <label>Vehicle Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/solution/03_DataModel/objects/Opportunity/fields/VIN__c.field-meta.xml
<CustomField>
    <fullName>VIN__c</fullName>
    <label>VIN</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/solution/10_InregrationIn/classes/ApiService.cls
public class ApiService {
    public static void stealOpportunities() {
        try {
            //String query = 'SELECT Id, Name, AmountAfterDiscount__c, DiscountPercent__c, VIN__c, VehicleBrand__c, VehicleType__c FROM Opportunity';
            String query = 'SELECT Id, Name, AmountAfterDiscount__c, DiscountPercent__c, VIN__c FROM Opportunity';
            HttpRequest req = new HttpRequest();
           req.setEndpoint('callout:mara/' + 'services/data/v61.0/query?q=' + EncodingUtil.urlEncode(query, 'UTF-8'));
            req.setMethod('GET');

            Http http = new Http();
            HTTPResponse res = http.send(req);

            if (res.getStatusCode() == 200) {
                System.debug('✅ Opportunities: ' + res.getBody());
            } else {
                System.debug('❌ Query failed: ' + res.getStatusCode() + ' ' + res.getBody());
            }

        } catch (Exception e) {
            System.debug('Error in callout: ' + e.getMessage());
        }
    }
}